/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSimulateRouteImport } from './routes/_authenticated/simulate'
import { Route as AuthenticatedPrioritiesRouteImport } from './routes/_authenticated/priorities'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedFactoryRouteImport } from './routes/_authenticated/factory'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulateRoute = AuthenticatedSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritiesRoute = AuthenticatedPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFactoryRoute = AuthenticatedFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/auth': typeof AuthRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/auth': typeof AuthRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/auth': typeof AuthRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/decisions'
    | '/factory'
    | '/forecast'
    | '/learning'
    | '/priorities'
    | '/settings'
    | '/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/decisions'
    | '/factory'
    | '/forecast'
    | '/learning'
    | '/priorities'
    | '/settings'
    | '/simulate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/decisions'
    | '/factory'
    | '/forecast'
    | '/learning'
    | '/priorities'
    | '/settings'
    | '/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulate': {
      id: '/_authenticated/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AuthenticatedSimulateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorities': {
      id: '/_authenticated/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof AuthenticatedPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factory': {
      id: '/_authenticated/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof AuthenticatedFactoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedFactoryRoute: typeof AuthenticatedFactoryRoute
  AuthenticatedPrioritiesRoute: typeof AuthenticatedPrioritiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulateRoute: typeof AuthenticatedSimulateRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedFactoryRoute: AuthenticatedFactoryRoute,
  AuthenticatedPrioritiesRoute: AuthenticatedPrioritiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulateRoute: AuthenticatedSimulateRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
