/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimulateRouteImport } from './routes/_authenticated/simulate'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPrioritiesRouteImport } from './routes/_authenticated/priorities'
import { Route as AuthenticatedOutputsRouteImport } from './routes/_authenticated/outputs'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedLinesRouteImport } from './routes/_authenticated/lines'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedInputsRouteImport } from './routes/_authenticated/inputs'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedFactoryRouteImport } from './routes/_authenticated/factory'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulateRoute = AuthenticatedSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritiesRoute = AuthenticatedPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutputsRoute = AuthenticatedOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinesRoute = AuthenticatedLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInputsRoute = AuthenticatedInputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFactoryRoute = AuthenticatedFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/inputs': typeof AuthenticatedInputsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/lines': typeof AuthenticatedLinesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/factory': typeof AuthenticatedFactoryRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/inputs': typeof AuthenticatedInputsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/lines': typeof AuthenticatedLinesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/factory': typeof AuthenticatedFactoryRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/inputs': typeof AuthenticatedInputsRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/lines': typeof AuthenticatedLinesRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/outputs': typeof AuthenticatedOutputsRoute
  '/_authenticated/priorities': typeof AuthenticatedPrioritiesRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simulate': typeof AuthenticatedSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/customers'
    | '/daily'
    | '/dashboard'
    | '/decisions'
    | '/factory'
    | '/forecast'
    | '/inputs'
    | '/learning'
    | '/lines'
    | '/materials'
    | '/orders'
    | '/outputs'
    | '/priorities'
    | '/products'
    | '/reports'
    | '/settings'
    | '/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/customers'
    | '/daily'
    | '/dashboard'
    | '/decisions'
    | '/factory'
    | '/forecast'
    | '/inputs'
    | '/learning'
    | '/lines'
    | '/materials'
    | '/orders'
    | '/outputs'
    | '/priorities'
    | '/products'
    | '/reports'
    | '/settings'
    | '/simulate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/assistant'
    | '/_authenticated/customers'
    | '/_authenticated/daily'
    | '/_authenticated/dashboard'
    | '/_authenticated/decisions'
    | '/_authenticated/factory'
    | '/_authenticated/forecast'
    | '/_authenticated/inputs'
    | '/_authenticated/learning'
    | '/_authenticated/lines'
    | '/_authenticated/materials'
    | '/_authenticated/orders'
    | '/_authenticated/outputs'
    | '/_authenticated/priorities'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulate': {
      id: '/_authenticated/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AuthenticatedSimulateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorities': {
      id: '/_authenticated/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof AuthenticatedPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outputs': {
      id: '/_authenticated/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof AuthenticatedOutputsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lines': {
      id: '/_authenticated/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof AuthenticatedLinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inputs': {
      id: '/_authenticated/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof AuthenticatedInputsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factory': {
      id: '/_authenticated/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof AuthenticatedFactoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedFactoryRoute: typeof AuthenticatedFactoryRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedInputsRoute: typeof AuthenticatedInputsRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedLinesRoute: typeof AuthenticatedLinesRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedOutputsRoute: typeof AuthenticatedOutputsRoute
  AuthenticatedPrioritiesRoute: typeof AuthenticatedPrioritiesRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulateRoute: typeof AuthenticatedSimulateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedFactoryRoute: AuthenticatedFactoryRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedInputsRoute: AuthenticatedInputsRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedLinesRoute: AuthenticatedLinesRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedOutputsRoute: AuthenticatedOutputsRoute,
  AuthenticatedPrioritiesRoute: AuthenticatedPrioritiesRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulateRoute: AuthenticatedSimulateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
